### ISSUE TITLE
Análisis de requisitos

### ISSUE THREAD

**Issue by javierherrer** [UNIZAR-30226-2021-11/plan-GADM-proyecto#10]
Hay que completar y detallar los requisitos preliminares incluidos en la propuesta técnica y económica.
Recordad que los requisitos deben ser completos, concretos, medibles cuando tenga sentido y lo menos
ambiguos posible. También es importante que estén identificados para facilitar su trazabilidad.

**Comment by javierherrer** [comment]
Completar los requisitos iniciales detallando mejor en qué consiste un torneo, una IA buena (que no sea solamente una función aleatoria), y un chat de usuarios.

**Comment by fuster92** [comment]
Necesito tener los requisitos para definir el calendario de tareas completamente, #9

**Comment by javierherrer** [comment]
Intenta corregir la tabla, que se salen por el margen derecho.

**Comment by samueltorresfau** [comment]
> Intenta corregir la tabla, que se salen por el margen derecho.
Este es el error, en mi caso me impide compilar el documento:

Overfull \hbox (1622.22554pt too wide) in paragraph at lines 292--338
 [] 
! Misplaced \noalign.
\hline ->\noalign 
                  {\ifnum 0=`}\fi \hrule \@height \arrayrulewidth \futurelet...
l.369         \hline
                    
?

**Comment by fuster92** [comment]
Arreglado en 7395e4fcb876e36249937cb1bde1718f3f6956d7 , importando el paquete longtable y utilizando cabeceras distintas.
La solución es de @mchavanel

**Comment by javierherrer** [comment]
- Partida basada en turnos ya está en anxo de reglas
- Eliminación de cuentas.
- RNF-9 aclarar si queremos meter toda la funcionalidad que conlleva (mejor quitar)

**Comment by mchavanel** [comment]
- Añadido un requisito funcional para detallar la eliminación de cuentas de los usuarios.
- RF2 eliminado.
- RNF8 y RNF9 eliminados (perfiles de administrador y usuario).

**Comment by javierherrer** [comment]
RF de eliminación de cuentas

**Comment by mchavanel** [comment]
Se añadió la última vez que se cerró el _issue_. No sé por qué ha dicho que no está en su versión.
