### ISSUE TITLE
Diseño del sistema

### ISSUE THREAD

**Issue by javierherrer** [UNIZAR-30226-2021-11/plan-GADM-proyecto#11]
• Diagramas arquitecturales (de módulos, de componentes y conectores, de distribución),
patrones de diseño y estilos arquitecturales que se aplicarán. Las interfaces (de módulos y de
componentes) son especialmente importantes. También lo son los protocolos de comunicación
entre componentes.
• Tecnologías elegidas (lenguajes de programación, componentes que se integrarán, API web
externas con las que se conectará etc.).
• Otros aspectos técnicos de interés (p.ej. si hay base de datos si va a ser SQL o NoSQL, si hay una
API Web va a ser REST[ful] o no, si algunas de las operaciones van a ser asíncronas o no, si va a
ser una aplicación móvil o de escritorio será nativa o se van a usar tecnologías web, cómo se van
a considerar los requisitos de seguridad o de prestaciones, cómo y dónde se harán las
instalaciones y despliegues etc.)
Hay que justificar todas las decisiones de diseño. Esto exige contestar a dos preguntas sobre cada
decisión: ¿qué alternativas se barajaron? y ¿por qué se eligió una y no las otras?

**Comment by javierherrer** [comment]
@fuster92 aquí puedes meter lo que pusiste en la propuesta técnica y económica si nos dice en la tutoría que estaba bien

**Comment by javierherrer** [comment]
Poner solo los diagramas que hagan falta, por ejemplos, clases o secuencia NO.
Mapa de navegación SÍ.

**Comment by javierherrer** [comment]
@Daniel-dgp se encarga del mapa de navegación

**Comment by javierherrer** [comment]
**Mapa de navegación**
- buscar usuario
- eliminar cuenta
- ventana emergente de pausa
- ventana emergente de ganador de una partida
- unirte a partida pausada (con mismo código que públicas?)
- mejorar entendibilidad de la navegación
- TORNEOS
- Navegación en movil

**Comment by javierherrer** [comment]
**Diagrama de arquitectura**
- Una parte de APIRest para la autentificación y otras peticiones
- Otra parte de WebSockets para el juego
- MVC en cliente: la capa de visualización genera eventos que son interpretados y hacen llamadas (3 capas?)

**Comment by javierherrer** [comment]
**Diagrama de despliegue**
- Diferencia entre servidor Web y nginx (EXPLICAR TODO MEJOR)
- Evitar dedicar tiempo extra a cosas que no aportan nada al proyecto

**Comment by javierherrer** [comment]
Preguntar ampliación mapa de navegación para los torneos

**Comment by samueltorresfau** [comment]
Hecho mapa navegación en Android (en [Drive](https://app.diagrams.net/#G1WoZ9XN-vtsBwSCF6JzDRuKFw-Y4dLxwA))

**Comment by javierherrer** [comment]
### FALTA
**Mapa de navegación**
- [x] buscar usuario
- [x] ventana emergente de pausa
- [x] ventana emergente de ganador de una partida
- [x] unirte a partida pausada (con mismo código que públicas?)
- [x] TORNEOS: añadir un botón en la pantalla de juego online que lleve a una pantalla similar a pantalla de listado de juegos online pero con el título "Torneo" y sin la opción de buscar partidas. Solo se te listarán las partidas a las que puedas entrar.
- [x] Campos de inicio de sesión "nombre de usuario"
- [x] Campos de registro
- [x] Código en Pantalla de elección de equipo

**Diagrama de arquitectura**
- [x] Una parte de APIRest para la autentificación y otras peticiones
- [x] Otra parte de WebSockets para el juego
- [x] MVC en cliente: la capa de visualización genera eventos que son interpretados y hacen llamadas (3 capas?)

**Comment by javierherrer** [comment]
Cerrado por @fuster92

**Comment by javierherrer** [comment]
**Mapa de navegación**
- [x] No dar la opción de jugar sin login, no tiene sentido ni usabilidad.
- [x] Log out tmpc tiene sentido en la pantalla de perfil
- [x] Cambiar botón de ajustes al perfil

**Comment by javierherrer** [comment]
**Diagrama de arquitectura**
Incluir los WS

**Comment by javierherrer** [comment]
Diagramas arquitectura en vectorial
