### ISSUE TITLE
Procesos de ejecución y control

### ISSUE THREAD

**Issue by javierherrer** [UNIZAR-30226-2021-11/plan-GADM-proyecto#4]
• Cómo se llevarán a cabo las comunicaciones internas, el registro de las decisiones tomadas en
reuniones, la redacción de las actas etc.
• Cómo se van a determinar las tareas a realizar y el reparto de las mismas a integrantes del
equipo en el día a día.
• Cómo se abordarán los temas de gestión del equipo humano (p.ej. la resolución de disputas).
• Qué se va a hacer respecto a medidas de progreso y monitorización del estado del proyecto (qué
se mira/mide, cada cuánto tiempo, qué se hace si se detectan problemas de rendimiento o
avance insuficiente o desviaciones respecto al plan inicial...).
• Cómo se hará la entrega de resultados.

**Comment by fuster92** [comment]
Pruebas añadiendo comentario desde la linea de comandos
