### ISSUE TITLE
Procesos técnicos

### ISSUE THREAD

**Issue by javierherrer** [UNIZAR-30226-2021-11/plan-GADM-proyecto#5]
Describir los métodos, herramientas y técnicas necesarios tanto para construir el software (p.ej.
herramientas de desarrollo) como para desplegarlo y probarlo (todos los necesarios para dar soporte a
los planes descritos a continuación).

**Comment by samueltorresfau** [comment]
En principio está todo comentado, cierro issue

**Comment by javierherrer** [comment]
Incluir versiones de todo el Software que se menciona.

**Comment by samueltorresfau** [comment]
En la página 15 jay una errata, pone 'Android' en lugar de 'Java', cuando se habla de porque se ha elegido esta tecnología por encima de Kotlin

**Comment by samueltorresfau** [comment]
Se debe comentar que finalmente las conexiones con el Backend no son seguras.

**Comment by samueltorresfau** [comment]
Corregido en el documento
