### ISSUE TITLE
Plan de construcción y despliegue del software

### ISSUE THREAD

**Issue by javierherrer** [UNIZAR-30226-2021-11/plan-GADM-proyecto#7]
• Cómo se construye e integra el software: si hay scripts de construcción automatizada o no (en
ese caso qué se usa, y cómo se garantiza que todos los participantes compilan igual y con las
mismas dependencias), qué se incluye en la construcción (descarga y actualización de
dependencias, compilación, ejecución de tests automáticos...) y cada cuánto se construye
(compila, integra, prueba) el sistema completo, cómo se configuran los computadores de los
desarrolladores.
• Cómo se despliega el software más allá de las máquinas de desarrollo: contenedores, máquinas
virtuales, servidor en cloud etc. y cómo se configuran esos entornos (rutas, usuarios y
contraseñas, puertos y otros elementos).

**Comment by javierherrer** [comment]
Especificar mejor donde están desplegadas las cosas (servidor web, GooglePlay...).
Pasos a seguir para el despliegue.

**Comment by samueltorresfau** [comment]
Se dice que el equipo de web emplea IntelliJ. Esto es incorrecto, han empleado Visual Studio junto a varias extensiones.
