### ISSUE TITLE
Plan de aseguramiento de la calidad

### ISSUE THREAD

**Issue by javierherrer** [UNIZAR-30226-2021-11/plan-GADM-proyecto#8]
• Guías para la documentación de diseño del software y otros documentos del proyecto, guías
para el diseño gráfico de las GUI (estética, usabilidad...).
• Actividades de control de calidad del código que se realizarán: revisiones de código por pares,
revisiones de requisitos o diagramas UML por pares, tipos de tests automáticos o manuales que
se llevarán a cabo.

**Comment by javierherrer** [comment]
IngSoft, poner pruebas que vayamos a hacer y explicarlas.

**Comment by javierherrer** [comment]
Falta meterlo como apartado en LaTeX que se me debió de pasar

**Comment by daniPerez99** [comment]
versión inicial realizada, si hay algo que modificar avisadme.

**Comment by javierherrer** [comment]
- Añadir pruebas de bajo nivel, de sobrecarga...
- Explicar mejor pruebas de funcionamiento de cada requisito (caja negra, caja blanca...?)
- Pruebas API: cliente falso sin comunicación (en servidor) y luego ya con comunicación

**Comment by javierherrer** [comment]
Desarrollar en qué las estamos usando las pruebas concretamente.
Las de caminos en simulación, las de equivalencia en Postman...

**Comment by javierherrer** [comment]
Mejorar la redacción
Eliminar pruebas de sobrecarga del servidor porque no da tiempo.
Errata "android pofiler"
"Vender mejor" la parte de las pruebas en GoLang del backend porque han costado muchas horas.
Pruebas unitarias no tienen mucho sentido porque son redundantes con las de caminos.
